export default {

    TOGGLE_MODAL: 'TOGGLE_MODAL',
    SIGN_OUT: 'SIGN_OUT',
    SET_USER: 'SET_USER',
    UPDATE_FRIDGE_INPUT: 'UPDATE_FRIDGE_INPUT',
    ADD_FRIDGE_ITEM: 'ADD_FRIDGE_ITEM',
    UPDATE_PANTRY_INPUT: 'UPDATE_PANTRY_INPUT',
    ADD_PANTRY_ITEM: 'ADD_PANTRY_ITEM'

}